apiVersion: apps/v1
kind: Deployment
metadata:
  name: emsp-account-card-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emsp-account-card-service
  template:
    metadata:
      labels:
        app: emsp-account-card-service
    spec:
      containers:
        - name: emsp-account-card-service
          image: 010686621503.dkr.ecr.us-west-2.amazonaws.com/emsp-account-card-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: JDBC_DATABASE_URL
              value: jdbc:postgresql://emspjun10a.cvgycsiso9qp.us-west-2.rds.amazonaws.com:5432/emsp
            - name: JDBC_DATABASE_USERNAME
              value: emspuser
            - name: JDBC_DATABASE_PASSWORD
              value: emsppass
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"