apiVersion: v1
kind: Service
metadata:
  name: emsp-account-card-service
spec:
  selector:
    app: emsp-account-card-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer