name: Java CI with Maven

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: emspuser
          POSTGRES_PASSWORD: emsppass
          POSTGRES_DB: emsp
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run tests
        run: mvn test
      - name: Build Docker image
        run: docker build -t emsp-account-card-service .
    env:
      JDBC_DATABASE_URL: jdbc:postgresql://localhost:5432/emsp
      JDBC_DATABASE_USERNAME: emspuser
      JDBC_DATABASE_PASSWORD: emsppass
